export const countryList = [
  {value: 'Albania', _id: 'AL'},
  {value: 'Åland Islands', _id: 'AX'},
  {value: 'Algeria', _id: 'DZ'},
  {value: 'American Samoa', _id: 'AS'},
  {value: 'Andorra', _id: 'AD'},
  {value: 'Angola', _id: 'AO'},
  {value: 'Anguilla', _id: 'AI'},
  {value: 'Antarctica', _id: 'AQ'},
  {value: 'Antigua and Barbuda', _id: 'AG'},
  {value: 'Argentina', _id: 'AR'},
  {value: 'Armenia', _id: 'AM'},
  {value: 'Aruba', _id: 'AW'},
  {value: 'Australia', _id: 'AU'},
  {value: 'Austria', _id: 'AT'},
  {value: 'Azerbaijan', _id: 'AZ'},
  {value: 'Bahamas (the)', _id: 'BS'},
  {value: 'Bahrain', _id: 'BH'},
  {value: 'Bangladesh', _id: 'BD'},
  {value: 'Barbados', _id: 'BB'},
  {value: 'Belarus', _id: 'BY'},
  {value: 'Belgium', _id: 'BE'},
  {value: 'Belize', _id: 'BZ'},
  {value: 'Benin', _id: 'BJ'},
  {value: 'Bermuda', _id: 'BM'},
  {value: 'Bhutan', _id: 'BT'},
  {value: 'Bolivia (Plurinational State of)', _id: 'BO'},
  {value: 'Bonaire, Sint Eustatius and Saba', _id: 'BQ'},
  {value: 'Bosnia and Herzegovina', _id: 'BA'},
  {value: 'Botswana', _id: 'BW'},
  {value: 'Bouvet Island', _id: 'BV'},
  {value: 'Brazil', _id: 'BR'},
  {value: 'British Indian Ocean Territory (the)', _id: 'IO'},
  {value: 'Brunei Darussalam', _id: 'BN'},
  {value: 'Bulgaria', _id: 'BG'},
  {value: 'Burkina Faso', _id: 'BF'},
  {value: 'Burundi', _id: 'BI'},
  {value: 'Cabo Verde', _id: 'CV'},
  {value: 'Cambodia', _id: 'KH'},
  {value: 'Cameroon', _id: 'CM'},
  {value: 'Canada', _id: 'CA'},
  {value: 'Cayman Islands (the)', _id: 'KY'},
  {value: 'Central African Republic (the)', _id: 'CF'},
  {value: 'Chad', _id: 'TD'},
  {value: 'Chile', _id: 'CL'},
  {value: 'China', _id: 'CN'},
  {value: 'Christmas Island', _id: 'CX'},
  {value: 'Cocos (Keeling) Islands (the)', _id: 'CC'},
  {value: 'Colombia', _id: 'CO'},
  {value: 'Comoros (the)', _id: 'KM'},
  {value: 'Congo (the Democratic Republic of the)', _id: 'CD'},
  {value: 'Congo (the)', _id: 'CG'},
  {value: 'Cook Islands (the)', _id: 'CK'},
  {value: 'Costa Rica', _id: 'CR'},
  {value: 'Croatia', _id: 'HR'},
  {value: 'Cuba', _id: 'CU'},
  {value: 'Curaçao', _id: 'CW'},
  {value: 'Cyprus', _id: 'CY'},
  {value: 'Czechia', _id: 'CZ'},
  {value: "Côte d'Ivoire", _id: 'CI'},
  {value: 'Denmark', _id: 'DK'},
  {value: 'Djibouti', _id: 'DJ'},
  {value: 'Dominica', _id: 'DM'},
  {value: 'Dominican Republic (the)', _id: 'DO'},
  {value: 'Ecuador', _id: 'EC'},
  {value: 'Egypt', _id: 'EG'},
  {value: 'El Salvador', _id: 'SV'},
  {value: 'Equatorial Guinea', _id: 'GQ'},
  {value: 'Eritrea', _id: 'ER'},
  {value: 'Estonia', _id: 'EE'},
  {value: 'Eswatini', _id: 'SZ'},
  {value: 'Ethiopia', _id: 'ET'},
  {value: 'Falkland Islands (the) [Malvinas]', _id: 'FK'},
  {value: 'Faroe Islands (the)', _id: 'FO'},
  {value: 'Fiji', _id: 'FJ'},
  {value: 'Finland', _id: 'FI'},
  {value: 'France', _id: 'FR'},
  {value: 'French Guiana', _id: 'GF'},
  {value: 'French Polynesia', _id: 'PF'},
  {value: 'French Southern Territories (the)', _id: 'TF'},
  {value: 'Gabon', _id: 'GA'},
  {value: 'Gambia (the)', _id: 'GM'},
  {value: 'Georgia', _id: 'GE'},
  {value: 'Germany', _id: 'DE'},
  {value: 'Ghana', _id: 'GH'},
  {value: 'Gibraltar', _id: 'GI'},
  {value: 'Greece', _id: 'GR'},
  {value: 'Greenland', _id: 'GL'},
  {value: 'Grenada', _id: 'GD'},
  {value: 'Guadeloupe', _id: 'GP'},
  {value: 'Guam', _id: 'GU'},
  {value: 'Guatemala', _id: 'GT'},
  {value: 'Guernsey', _id: 'GG'},
  {value: 'Guinea', _id: 'GN'},
  {value: 'Guinea-Bissau', _id: 'GW'},
  {value: 'Guyana', _id: 'GY'},
  {value: 'Haiti', _id: 'HT'},
  {value: 'Heard Island and McDonald Islands', _id: 'HM'},
  {value: 'Holy See (the)', _id: 'VA'},
  {value: 'Honduras', _id: 'HN'},
  {value: 'Hong Kong', _id: 'HK'},
  {value: 'Hungary', _id: 'HU'},
  {value: 'Iceland', _id: 'IS'},
  {value: 'India', _id: 'IN'},
  {value: 'Indonesia', _id: 'ID'},
  {value: 'Iran (Islamic Republic of)', _id: 'IR'},
  {value: 'Iraq', _id: 'IQ'},
  {value: 'Ireland', _id: 'IE'},
  {value: 'Isle of Man', _id: 'IM'},
  {value: 'Israel', _id: 'IL'},
  {value: 'Italy', _id: 'IT'},
  {value: 'Jamaica', _id: 'JM'},
  {value: 'Japan', _id: 'JP'},
  {value: 'Jersey', _id: 'JE'},
  {value: 'Jordan', _id: 'JO'},
  {value: 'Kazakhstan', _id: 'KZ'},
  {value: 'Kenya', _id: 'KE'},
  {value: 'Kiribati', _id: 'KI'},
  {value: "Korea (the Democratic People's Republic of)", _id: 'KP'},
  {value: 'Korea (the Republic of)', _id: 'KR'},
  {value: 'Kuwait', _id: 'KW'},
  {value: 'Kyrgyzstan', _id: 'KG'},
  {value: "Lao People's Democratic Republic (the)", _id: 'LA'},
  {value: 'Latvia', _id: 'LV'},
  {value: 'Lebanon', _id: 'LB'},
  {value: 'Lesotho', _id: 'LS'},
  {value: 'Liberia', _id: 'LR'},
  {value: 'Libya', _id: 'LY'},
  {value: 'Liechtenstein', _id: 'LI'},
  {value: 'Lithuania', _id: 'LT'},
  {value: 'Luxembourg', _id: 'LU'},
  {value: 'Macao', _id: 'MO'},
  {value: 'Madagascar', _id: 'MG'},
  {value: 'Malawi', _id: 'MW'},
  {value: 'Malaysia', _id: 'MY'},
  {value: 'Maldives', _id: 'MV'},
  {value: 'Mali', _id: 'ML'},
  {value: 'Malta', _id: 'MT'},
  {value: 'Marshall Islands (the)', _id: 'MH'},
  {value: 'Martinique', _id: 'MQ'},
  {value: 'Mauritania', _id: 'MR'},
  {value: 'Mauritius', _id: 'MU'},
  {value: 'Mayotte', _id: 'YT'},
  {value: 'Mexico', _id: 'MX'},
  {value: 'Micronesia (Federated States of)', _id: 'FM'},
  {value: 'Moldova (the Republic of)', _id: 'MD'},
  {value: 'Monaco', _id: 'MC'},
  {value: 'Mongolia', _id: 'MN'},
  {value: 'Montenegro', _id: 'ME'},
  {value: 'Montserrat', _id: 'MS'},
  {value: 'Morocco', _id: 'MA'},
  {value: 'Mozambique', _id: 'MZ'},
  {value: 'Myanmar', _id: 'MM'},
  {value: 'Namibia', _id: 'NA'},
  {value: 'Nauru', _id: 'NR'},
  {value: 'Nepal', _id: 'NP'},
  {value: 'Netherlands (the)', _id: 'NL'},
  {value: 'New Caledonia', _id: 'NC'},
  {value: 'New Zealand', _id: 'NZ'},
  {value: 'Nicaragua', _id: 'NI'},
  {value: 'Niger (the)', _id: 'NE'},
  {value: 'Nigeria', _id: 'NG'},
  {value: 'Niue', _id: 'NU'},
  {value: 'Norfolk Island', _id: 'NF'},
  {value: 'Northern Mariana Islands (the)', _id: 'MP'},
  {value: 'Norway', _id: 'NO'},
  {value: 'Oman', _id: 'OM'},
  {value: 'Pakistan', _id: 'PK'},
  {value: 'Palau', _id: 'PW'},
  {value: 'Palestine, State of', _id: 'PS'},
  {value: 'Panama', _id: 'PA'},
  {value: 'Papua New Guinea', _id: 'PG'},
  {value: 'Paraguay', _id: 'PY'},
  {value: 'Peru', _id: 'PE'},
  {value: 'Philippines (the)', _id: 'PH'},
  {value: 'Pitcairn', _id: 'PN'},
  {value: 'Poland', _id: 'PL'},
  {value: 'Portugal', _id: 'PT'},
  {value: 'Puerto Rico', _id: 'PR'},
  {value: 'Qatar', _id: 'QA'},
  {value: 'Republic of North Macedonia', _id: 'MK'},
  {value: 'Romania', _id: 'RO'},
  {value: 'Russian Federation (the)', _id: 'RU'},
  {value: 'Rwanda', _id: 'RW'},
  {value: 'Réunion', _id: 'RE'},
  {value: 'Saint Barthélemy', _id: 'BL'},
  {value: 'Saint Helena, Ascension and Tristan da Cunha', _id: 'SH'},
  {value: 'Saint Kitts and Nevis', _id: 'KN'},
  {value: 'Saint Lucia', _id: 'LC'},
  {value: 'Saint Martin (French part)', _id: 'MF'},
  {value: 'Saint Pierre and Miquelon', _id: 'PM'},
  {value: 'Saint Vincent and the Grenadines', _id: 'VC'},
  {value: 'Samoa', _id: 'WS'},
  {value: 'San Marino', _id: 'SM'},
  {value: 'Sao Tome and Principe', _id: 'ST'},
  {value: 'Saudi Arabia', _id: 'SA'},
  {value: 'Senegal', _id: 'SN'},
  {value: 'Serbia', _id: 'RS'},
  {value: 'Seychelles', _id: 'SC'},
  {value: 'Sierra Leone', _id: 'SL'},
  {value: 'Singapore', _id: 'SG'},
  {value: 'Sint Maarten (Dutch part)', _id: 'SX'},
  {value: 'Slovakia', _id: 'SK'},
  {value: 'Slovenia', _id: 'SI'},
  {value: 'Solomon Islands', _id: 'SB'},
  {value: 'Somalia', _id: 'SO'},
  {value: 'South Africa', _id: 'ZA'},
  {value: 'South Georgia and the South Sandwich Islands', _id: 'GS'},
  {value: 'South Sudan', _id: 'SS'},
  {value: 'Spain', _id: 'ES'},
  {value: 'Sri Lanka', _id: 'LK'},
  {value: 'Sudan (the)', _id: 'SD'},
  {value: 'Surivalue', _id: 'SR'},
  {value: 'Svalbard and Jan Mayen', _id: 'SJ'},
  {value: 'Sweden', _id: 'SE'},
  {value: 'Switzerland', _id: 'CH'},
  {value: 'Syrian Arab Republic', _id: 'SY'},
  {value: 'Taiwan (Province of China)', _id: 'TW'},
  {value: 'Tajikistan', _id: 'TJ'},
  {value: 'Tanzania, United Republic of', _id: 'TZ'},
  {value: 'Thailand', _id: 'TH'},
  {value: 'Timor-Leste', _id: 'TL'},
  {value: 'Togo', _id: 'TG'},
  {value: 'Tokelau', _id: 'TK'},
  {value: 'Tonga', _id: 'TO'},
  {value: 'Trinidad and Tobago', _id: 'TT'},
  {value: 'Tunisia', _id: 'TN'},
  {value: 'Turkey', _id: 'TR'},
  {value: 'Turkmenistan', _id: 'TM'},
  {value: 'Turks and Caicos Islands (the)', _id: 'TC'},
  {value: 'Tuvalu', _id: 'TV'},
  {value: 'Uganda', _id: 'UG'},
  {value: 'Ukraine', _id: 'UA'},
  {value: 'United Arab Emirates (the)', _id: 'AE'},
  {
    value: 'United Kingdom of Great Britain and Northern Ireland (the)',
    _id: 'GB',
  },
  {value: 'United States Minor Outlying Islands (the)', _id: 'UM'},
  {value: 'United States of America (the)', _id: 'US'},
  {value: 'Uruguay', _id: 'UY'},
  {value: 'Uzbekistan', _id: 'UZ'},
  {value: 'Vanuatu', _id: 'VU'},
  {value: 'Venezuela (Bolivarian Republic of)', _id: 'VE'},
  {value: 'Viet Nam', _id: 'VN'},
  {value: 'Virgin Islands (British)', _id: 'VG'},
  {value: 'Virgin Islands (U.S.)', _id: 'VI'},
  {value: 'Wallis and Futuna', _id: 'WF'},
  {value: 'Western Sahara', _id: 'EH'},
  {value: 'Yemen', _id: 'YE'},
  {value: 'Zambia', _id: 'ZM'},
  {value: 'Zimbabwe', _id: 'ZW'},
];
